"""edit country

Revision ID: c23ffc119a12
Revises: a8e371e37f8a
Create Date: 2023-11-08 18:01:01.298402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c23ffc119a12'
down_revision: Union[str, None] = 'a8e371e37f8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('iso_code', sa.String(length=3), nullable=False))
    op.add_column('countries', sa.Column('name_en', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'countries', ['iso_code'])
    op.drop_column('countries', 'code')
    # ### end Alembic commands ###

    # conn = op.get_bind()
    # conn.execute("INSERT INTO countries (iso_code, name, name_en) VALUES ('UA','Україна', 'Ukraine') on conflict do nothing")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('code', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'countries', type_='unique')
    op.drop_column('countries', 'name_en')
    op.drop_column('countries', 'iso_code')
    # ### end Alembic commands ###
